packages:
  granzscientific.bm1-base: !include base.yaml

dashboard_import:
  package_import_url: github://granzscientific/gc1-geiger-counter/gs-gc1-geiger-counter.yaml

esphome:
  name_add_mac_suffix: true
